export enum MovieGenre {
  action = 'Action',
  adventure = 'Adventure',
  animation = 'Animation',
  biography = 'Biography',
  comedy = 'Comedy',
  crime = 'Crime',
  documentary = 'Documentary',
  drama = 'Drama',
  family = 'Family',
  fantasy = 'Fantasy',
  filmNoir = 'Film Noir',
  noir = 'Noir',
  history = 'History',
  horror = 'Horror',
  music = 'Music',
  musical = 'Musical',
  mystery = 'Mystery',
  romance = 'Romance',
  sciFi = 'Sci-Fi',
  shortFilm = 'Short Film',
  sport = 'Sport',
  superhero = 'Superhero',
  thriller = 'Thriller',
  war = 'War',
  western = 'Western'
}

export const movieGenreResolver: Record<string, MovieGenre> = {
  ACTION: MovieGenre.action,
  ADVENTURE: MovieGenre.adventure,
  ANIMATION: MovieGenre.animation,
  BIOGRAPHY: MovieGenre.biography,
  COMEDY: MovieGenre.comedy,
  CRIME: MovieGenre.crime,
  DOCUMENTARY: MovieGenre.documentary,
  DRAMA: MovieGenre.drama,
  FAMILY: MovieGenre.family,
  FANTASY: MovieGenre.fantasy,
  FILM_NOIR: MovieGenre.filmNoir,
  HISTORY: MovieGenre.history,
  HORROR: MovieGenre.horror,
  MUSIC: MovieGenre.music,
  MUSICAL: MovieGenre.musical,
  MYSTERY: MovieGenre.mystery,
  ROMANCE: MovieGenre.romance,
  SCI_FI: MovieGenre.sciFi,
  SHORT_FILM: MovieGenre.shortFilm,
  SPORT: MovieGenre.sport,
  SUPERHERO: MovieGenre.superhero,
  THRILLER: MovieGenre.thriller,
  WAR: MovieGenre.war,
  WESTERN: MovieGenre.western
};
